BanHang/Models/Product.cs
namespace BanHang.Models
{
	using System;
	using System.Collections.Generic;
	using System.ComponentModel;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Data.Entity.Spatial;
	using System.Web.Mvc;

	[Table("Product")]
	public partial class Product
	{
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
		public Product()
		{
			
			Order_Details = new HashSet<Order_Details>();
			ProductImages = new HashSet<ProductImage>();
		}

		[Key]
		[DisplayName("ID Sản Phẩm")]
		public int IDProduct { get; set; }

		[StringLength(50)]
		[DisplayName("Tên")]
		[Required(ErrorMessage = "Tên sản phẩm là bắt buộc")]
		public string Name { get; set; }

		[StringLength(255)]
		[DisplayName("Tiêu đề SEO")]
		public string SeoTitle { get; set; }

		[DisplayName("Mô tả")]
		[AllowHtml]
		public string Description { get; set; }
		[AllowHtml]

		[DisplayName("Chi tiết")]
		public string Detail { get; set; }

		[DisplayName("Hình ảnh")]
		public string Image { get; set; }

		[DisplayName("Giá")]
		
		public decimal? Price { get; set; }

		[DisplayName("Giá Khuyến Mãi")]
		
		public decimal? PriceSale { get; set; }
		[DisplayName("Giá gốc")]
		
		public decimal? PriceOrigin { get; set; }

		[StringLength(10)]
		[DisplayName("Kích thước")]
		public string Size { get; set; }

		[DisplayName("Số lượng")]
		public int? Quantity { get; set; }

		[DisplayName("Hiển thị trang chủ")]
		public bool? IsHome { get; set; }

		[DisplayName("Sản phẩm khuyến mãi")]
		public bool? IsSale { get; set; }

		[DisplayName("Hoạt động")]
		public bool? IsActive { get; set; }

		[DisplayName("Sản phẩm nổi bật")]
		public bool? IsHot { get; set; }

		[StringLength(50)]
		[DisplayName("Người tạo")]
		public string CreatedBy { get; set; }

		[DisplayName("Ngày tạo")]
		public DateTime? CreatedDate { get; set; }

		[StringLength(50)]
		[DisplayName("Người sửa đổi")]
		public string ModifiedBy { get; set; }

		[DisplayName("Ngày sửa đổi")]
		public DateTime? ModifiedDate { get; set; }

		[DisplayName("ID Danh mục sản phẩm")]
		public int? ProductCategoryID { get; set; }

		[DisplayName("Alias")]
		public string Alias { get; set; }

		

		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		public virtual ICollection<Order_Details> Order_Details { get; set; }

		public virtual ProductCategory ProductCategory { get; set; }

		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		public virtual ICollection<ProductImage> ProductImages { get; set; }
	}
}

BanHang/Areas/Admin/Controllers/ProductCategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BanHang.Models;

namespace BanHang.Areas.Admin.Controllers
{
    public class ProductCategoriesController : Controller
    {
        private BanHangContext db = new BanHangContext();

        // GET: Admin/ProductCategories
        public ActionResult Index()
        {
			if (Session["Tendangnhap1"] == null)
			{
				return RedirectToAction("Index", "Login");
			}
			return View(db.ProductCategories.ToList());
        }

        // GET: Admin/ProductCategories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductCategory productCategory = db.ProductCategories.Find(id);
            if (productCategory == null)
            {
                return HttpNotFound();
            }
            return View(productCategory);
        }

        // GET: Admin/ProductCategories/Create
        public ActionResult Create()
        {
            return View();
        }

		// POST: Admin/ProductCategories/Create
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Create([Bind(Include = "ProductCategoryID,Name,SeoTitle,Image,CreatedBy,CreatedDate,ModifiedBy,ModifiedDate,Alias")] ProductCategory productCategory)
		{
			if (ModelState.IsValid)
			{
				// Kiểm tra xem Name đã tồn tại trong cơ sở dữ liệu chưa
				if (db.ProductCategories.Any(c => c.Name == productCategory.Name))
				{
					ModelState.AddModelError("Name", "Tên danh mục đã tồn tại trong cơ sở dữ liệu.");
					return View(productCategory);
				}

				productCategory.CreatedDate = DateTime.Now;
				productCategory.ModifiedDate = DateTime.Now;
				productCategory.Alias = BanHang.Models.Common.Filter.FilterChar(productCategory.Name);

				db.ProductCategories.Add(productCategory);
				db.SaveChanges();
				return RedirectToAction("Index");
			}

			return View(productCategory);
		}


		// GET: Admin/ProductCategories/Edit/5
		public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductCategory productCategory = db.ProductCategories.Find(id);
            if (productCategory == null)
            {
                return HttpNotFound();
            }
            return View(productCategory);
        }

		// POST: Admin/ProductCategories/Edit/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Edit([Bind(Include = "ProductCategoryID,Name,SeoTitle,Image,CreatedBy,CreatedDate,ModifiedBy,ModifiedDate,Alias")] ProductCategory productCategory)
		{
			if (ModelState.IsValid)
			{
				// Lấy thông tin danh mục sản phẩm từ cơ sở dữ liệu
				var existingCategory = db.ProductCategories.Find(productCategory.ProductCategoryID);
				if (existingCategory != null)
				{
					// Gán giá trị CreatedBy và CreatedDate từ danh mục sản phẩm đã lưu trong cơ sở dữ liệu cho đối tượng productCategory
					productCategory.CreatedBy = existingCategory.CreatedBy;
					productCategory.CreatedDate = existingCategory.CreatedDate;

					// Thêm dòng này để cập nhật giá trị ModifiedDate
					productCategory.ModifiedDate = DateTime.Now;

					// Tạo Alias mới từ tên danh mục sản phẩm đã chỉnh sửa
					productCategory.Alias = BanHang.Models.Common.Filter.FilterChar(productCategory.Name);

					// Cập nhật thông tin danh mục sản phẩm trong cơ sở dữ liệu
					db.Entry(existingCategory).CurrentValues.SetValues(productCategory);
					db.SaveChanges();
					return RedirectToAction("Index");
				}
				else
				{
					return HttpNotFound();
				}
			}
			return View(productCategory);
		}


		// GET: Admin/ProductCategories/Delete/5
		public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductCategory productCategory = db.ProductCategories.Find(id);
            if (productCategory == null)
            {
                return HttpNotFound();
            }
            return View(productCategory);
        }

        // POST: Admin/ProductCategories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ProductCategory productCategory = db.ProductCategories.Find(id);
            db.ProductCategories.Remove(productCategory);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BanHang/Areas/Admin/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BanHang.Models;
using PagedList;

namespace BanHang.Areas.Admin.Controllers
{
	public class ProductsController : Controller
	{
		private BanHangContext db = new BanHangContext();

		// GET: Admin/Products
		public ActionResult Index(string searchTitle, int? page)
		{
			if (Session["Tendangnhap1"] == null)
			{
				return RedirectToAction("Index", "Login");
			}
			var news = db.Products.AsQueryable();

			if (!string.IsNullOrEmpty(searchTitle))
			{
				news = news.Where(n => n.Name.Contains(searchTitle));
			}

			int pageSize = 4; // Số lượng tin tức trên mỗi trang
			int pageNumber = (page ?? 1); // Số trang hiện tại, mặc định là 1 nếu không có giá trị

			return View(news.OrderBy(n => n.IDProduct).ToPagedList(pageNumber, pageSize));
		}

		// GET: Admin/Products/Details/5
		public ActionResult Details(int? id)
		{
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			Product product = db.Products.Find(id);
			if (product == null)
			{
				return HttpNotFound();
			}
			return View(product);
		}

		// GET: Admin/Products/Create
		public ActionResult Create()
		{
			ViewBag.ProductCategoryID = new SelectList(db.ProductCategories, "ProductCategoryID", "Name");
			return View();
		}

		// POST: Admin/Products/Create
		// To protect from overposting attacks, enable the specific properties you want to bind to, for 
		// more details see https://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Create([Bind(Include = "IDProduct,Name,SeoTitle,Description,Detail,Image,Price,PriceSale,PriceOrigin,Size,Quantity,IsHome,IsSale,IsActive,IsHot,CreatedBy,CreatedDate,ModifiedBy,ModifiedDate,ProductCategoryID,Alias")] Product product)
		{
			if (ModelState.IsValid)
			{
				// Kiểm tra xem tên sản phẩm đã tồn tại trong cơ sở dữ liệu chưa
				if (db.Products.Any(p => p.Name == product.Name))
				{
					ModelState.AddModelError("Name", "Tên sản phẩm đã tồn tại trong cơ sở dữ liệu.");
					ViewBag.ProductCategoryID = new SelectList(db.ProductCategories, "ProductCategoryID", "Name", product.ProductCategoryID);
					return View(product);
				}

				// Set CreatedDate to current datetime
				product.CreatedDate = DateTime.Now;

				// Set ModifiedDate to current datetime
				product.ModifiedDate = DateTime.Now;

				// Set Alias using FilterChar method
				product.Alias = BanHang.Models.Common.Filter.FilterChar(product.Name);

				db.Products.Add(product);
				db.SaveChanges();
				return RedirectToAction("Index");
			}

			ViewBag.ProductCategoryID = new SelectList(db.ProductCategories, "ProductCategoryID", "Name", product.ProductCategoryID);
			return View(product);
		}

		// GET: Admin/Products/Edit/5
		public ActionResult Edit(int? id)
		{
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			Product product = db.Products.Find(id);
			if (product == null)
			{
				return HttpNotFound();
			}
			ViewBag.ProductCategoryID = new SelectList(db.ProductCategories, "ProductCategoryID", "Name", product.ProductCategoryID);
			return View(product);
		}

		// POST: Admin/Products/Edit/5
		// To protect from overposting attacks, enable the specific properties you want to bind to, for 
		// more details see https://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Edit([Bind(Include = "IDProduct,Name,SeoTitle,Description,Detail,Image,Price,PriceSale,PriceOrigin,Size,Quantity,IsHome,IsSale,IsActive,IsHot,CreatedBy,CreatedDate,ModifiedBy,ModifiedDate,ProductCategoryID,Alias")] Product product)
		{
			if (ModelState.IsValid)
			{
				var existingProduct = db.Products.Find(product.IDProduct);
				if (existingProduct != null)
				{
					product.CreatedDate = existingProduct.CreatedDate;
					product.CreatedBy = existingProduct.CreatedBy;
					product.ModifiedDate = DateTime.Now; // Cập nhật ModifiedDate mới

					product.Alias = BanHang.Models.Common.Filter.FilterChar(product.Name); // Tạo alias mới từ tên sản phẩm đã chỉnh sửa
					db.Entry(existingProduct).CurrentValues.SetValues(product);
					// Lưu các thay đổi vào cơ sở dữ liệu
					db.SaveChanges();
					return RedirectToAction("Index");
				}
				else
				{
					return HttpNotFound();
				}
			}
			ViewBag.ProductCategoryID = new SelectList(db.ProductCategories, "ProductCategoryID", "Name", product.ProductCategoryID);
			return View(product);
		}

		// GET: Admin/Products/Delete/5
		public ActionResult Delete(int? id)
		{
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			Product product = db.Products.Find(id);
			if (product == null)
			{
				return HttpNotFound();
			}
			return View(product);
		}

		// POST: Admin/Products/Delete/5
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public ActionResult DeleteConfirmed(int id)
		{
			Product product = db.Products.Find(id);
			db.Products.Remove(product);
			db.SaveChanges();
			return RedirectToAction("Index");
		}

		protected override void Dispose(bool disposing)
		{
			if (disposing)
			{
				db.Dispose();
			}
			base.Dispose(disposing);
		}
	}
}

BanHang/Controllers/MenuController.cs
using BanHang.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BanHang.Controllers
{
    public class MenuController : Controller
    {
        private BanHangContext db = new BanHangContext();
        // GET: Menu
        public ActionResult Index()
        {
            return View();
        }
		public ActionResult MenuTop()
		{
			var items = db.Categories.OrderBy(x => x.Position).ToList();
			return PartialView("_MenuTop", items);
		}

		public ActionResult MenuProductCategory()
		{
			var items = db.ProductCategories.ToList();
			return PartialView("_MenuProductCategory", items);
		}
		public ActionResult MenuLeft(int? id)
		{
			if (id != null)
			{
				ViewBag.CateId = id;
			}
			var items = db.ProductCategories.ToList();
			return PartialView("_MenuLeft", items);
		}

		public ActionResult MenuArrivals()
		{
			var items = db.ProductCategories.ToList();
			return PartialView("_MenuArrivals", items);
		}
	}
}

BanHang/Controllers/ProductsController.cs
using BanHang.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace BanHang.Controllers
{
    public class ProductsController : Controller
    {
        private BanHangContext db = new BanHangContext();
		// GET: Products
		public ActionResult Index(string searchTitle, int? page)
		{
			
			var news = db.Products.AsQueryable();

			if (!string.IsNullOrEmpty(searchTitle))
			{
				news = news.Where(n => n.Name.Contains(searchTitle));
			}

			int pageSize = 8; // Số lượng tin tức trên mỗi trang
			int pageNumber = (page ?? 1); // Số trang hiện tại, mặc định là 1 nếu không có giá trị

			return View(news.OrderBy(n => n.IDProduct).ToPagedList(pageNumber, pageSize));
		}
		public ActionResult Partial_ItemsByCateId()
		{
			var items = db.Products.Take(10).ToList();
			return PartialView(items);
		}
		public ActionResult Partial_ProductSales()
		{
			var items = db.Products.Take(12).ToList();
			return PartialView(items);
		}
		//public ActionResult Detail(string alias, int id)
		//{
		//	var item = db.Products.Find(id);
		//	if (item != null)
		//	{
		//		db.Products.Attach(item);
		//		item.ViewCount = item.ViewCount + 1;
		//		db.Entry(item).Property(x => x.ViewCount).IsModified = true;
		//		db.SaveChanges();
		//	}

		//	return View(item);
		//}
		public ActionResult ProductCategory(string alias, int id, string searchTitle, int? page)
		{
			var items = db.Products.Where(x => x.ProductCategoryID == id);

			// Tìm kiếm theo tiêu đề nếu có từ khóa tìm kiếm được cung cấp
			if (!string.IsNullOrEmpty(searchTitle))
			{
				items = items.Where(n => n.Name.Contains(searchTitle));
			}

			int pageSize = 8; // Số lượng sản phẩm trên mỗi trang
			int pageNumber = (page ?? 1); // Số trang hiện tại, mặc định là 1 nếu không có giá trị

			// Sắp xếp và phân trang danh sách sản phẩm
			var pagedItems = items.OrderBy(n => n.IDProduct).ToPagedList(pageNumber, pageSize);

			var cate = db.ProductCategories.Find(id);
			if (cate != null)
			{
				ViewBag.CateName = cate.Name;
			}

			ViewBag.CateId = id;
			ViewBag.SearchTitle = searchTitle;

			return View(pagedItems);
		}
		public ActionResult Details(int? id)
		{
			var item = db.Products.Find(id);
			//if (item != null)
			//{
			//	db.Products.Attach(item);
			//	item.ViewCount = item.ViewCount + 1;
			//	db.Entry(item).Property(x => x.ViewCount).IsModified = true;
			//	db.SaveChanges();
			//}

			return View(item);
		}
		

	}
}

BanHang/Views/Products/ProductCategory.cshtml
@model IPagedList<BanHang.Models.Product>
@using PagedList.Mvc;
@using PagedList;
<link rel="stylesheet" type="text/css" href="~/Content/assets/styles/categories_styles.css">
<link rel="stylesheet" type="text/css" href="~/Content/assets/styles/categories_responsive.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
<div class="container product_section_container">
    <div class="row">
        <div class="col product_section clearfix">

            <!-- Breadcrumbs -->

            <div class="breadcrumbs d-flex flex-row align-items-center">
                <ul>
                    <li><a href="/Home/Index">Trang Chủ</a></li>
                    <li class="active"><a href="/"><i class="fa fa-angle-right" aria-hidden="true"></i>@ViewBag.CateName</a></li>
                </ul>
            </div>
            <div class="row justify-content-center" style="padding: 10px; margin-top: -15px;">
                <div class="col-6">
                    @using (Html.BeginForm("ProductCategory", "Products", FormMethod.Get, new { }))
                    {
                        <div class="input-group" style="margin-top:-42px">
                            @Html.TextBox("SearchTitle", null, new { @class = "form-control", placeholder = "Tìm kiếm theo tên sản phẩm..." })
                            <div class="input-group-append">
                                <button type="submit" class="btn btn-info">Tìm kiếm</button>
                            </div>
                        </div>
                    }
                </div>
            </div>
            <!-- Sidebar -->

            <div class="sidebar">
                <div class="sidebar_section">
                    <div class="sidebar_title">
                        <h5>Danh Mục Sản Phẩm</h5>
                    </div>
                    @Html.Action("MenuLeft", "Menu")
                </div>

                <!-- Price Range Filtering -->
                <div class="sidebar_section">
                    <div class="sidebar_title">
                        <h5>Mức Gía</h5>
                    </div>
                    <p>
                        <input type="text" id="amount" readonly style="border:0; color:#f6931f; font-weight:bold;">
                    </p>
                    <div id="slider-range"></div>
                    <div class="filter_button"><span>Lọc</span></div>

                    <hr />
                    @*@Html.Action("Refresh", "Home")*@
                </div>

                <!-- Sizes -->
                @*<div class="sidebar_section">
                        <div class="sidebar_title">
                            <h5>Sizes</h5>
                        </div>
                        <ul class="checkboxes">
                            <li><i class="fa fa-square-o" aria-hidden="true"></i><span>S</span></li>
                            <li class="active"><i class="fa fa-square" aria-hidden="true"></i><span>M</span></li>
                            <li><i class="fa fa-square-o" aria-hidden="true"></i><span>L</span></li>
                            <li><i class="fa fa-square-o" aria-hidden="true"></i><span>XL</span></li>
                            <li><i class="fa fa-square-o" aria-hidden="true"></i><span>XXL</span></li>
                        </ul>
                    </div>*@

                <!-- Color -->
                @*<div class="sidebar_section">
                        <div class="sidebar_title">
                            <h5>Color</h5>
                        </div>
                        <ul class="checkboxes">
                            <li><i class="fa fa-square-o" aria-hidden="true"></i><span>Black</span></li>
                            <li class="active"><i class="fa fa-square" aria-hidden="true"></i><span>Pink</span></li>
                            <li><i class="fa fa-square-o" aria-hidden="true"></i><span>White</span></li>
                            <li><i class="fa fa-square-o" aria-hidden="true"></i><span>Blue</span></li>
                            <li><i class="fa fa-square-o" aria-hidden="true"></i><span>Orange</span></li>
                            <li><i class="fa fa-square-o" aria-hidden="true"></i><span>White</span></li>
                            <li><i class="fa fa-square-o" aria-hidden="true"></i><span>Blue</span></li>
                            <li><i class="fa fa-square-o" aria-hidden="true"></i><span>Orange</span></li>
                            <li><i class="fa fa-square-o" aria-hidden="true"></i><span>White</span></li>
                            <li><i class="fa fa-square-o" aria-hidden="true"></i><span>Blue</span></li>
                            <li><i class="fa fa-square-o" aria-hidden="true"></i><span>Orange</span></li>
                        </ul>
                        <div class="show_more">
                            <span><span>+</span>Show More</span>
                        </div>
                    </div>*@

            </div>

            <!-- Main Content -->

            <div class="main_content">

                <!-- Products -->

                <div class="products_iso">
                    <div class="row">
                        <div class="col">

                            <!-- Product Sorting -->

                            <div class="product_sorting_container product_sorting_container_top">
                                <ul class="product_sorting">
                                    <li>
                                        <span class="type_sorting_text">Sắp xếp mặc định</span>
                                        <i class="fa fa-angle-down"></i>
                                        <ul class="sorting_type">
                                            <li class="type_sorting_btn" data-isotope-option='{ "sortBy": "original-order" }'><span>Mặc định</span></li>
                                            <li class="type_sorting_btn" data-isotope-option='{ "sortBy": "price" }'><span>Giá</span></li>
                                            <li class="type_sorting_btn" data-isotope-option='{ "sortBy": "name" }'><span>Tên sản phẩm</span></li>
                                        </ul>
                                    </li>
                                    <li>
                                        <span>Hiển Thị</span>
                                        <span class="num_sorting_text">6</span>
                                        <i class="fa fa-angle-down"></i>
                                        <ul class="sorting_num">
                                            <li class="num_sorting_btn"><span>6</span></li>
                                            <li class="num_sorting_btn"><span>12</span></li>
                                            <li class="num_sorting_btn"><span>24</span></li>
                                        </ul>
                                    </li>
                                </ul>
                                <div class="pages d-flex flex-row align-items-center">
                                    <div class="page_current">
                                        <span>1</span>
                                        <ul class="page_selection">
                                            <li><a href="#">1</a></li>
                                            <li><a href="#">2</a></li>
                                            <li><a href="#">3</a></li>
                                        </ul>
                                    </div>
                                    <div class="page_total"><span>of</span> 3</div>
                                    <div id="next_page" class="page_next"><a href="#"><i class="fa fa-long-arrow-right" aria-hidden="true"></i></a></div>
                                </div>

                            </div>

                            <!-- Product Grid -->

                            <div class="product-grid">

                                <!-- Product 1 -->
                                @if (Model != null && Model.Any())
                                {
                                    foreach (var item in Model)
                                    {
                                        //var strImge = "";
                                        //var img = item.ProductImage.FirstOrDefault(x => x.IsDefault);
                                        //if (img != null)
                                        //{
                                        //    strImge = img.Image;
                                        //}
                                        <div class="product-item @item.ProductCategory.Alias">
                                            <div class="product discount product_filter">
                                                <div class="product_image">
                                                    <img style="width:221px;height:221px;" src="@item.Image" alt="@item.Name">
                                                </div>
                                                <div class="favorite favorite_left"></div>
                                                @if (item.PriceSale > 0)
                                                {
                                                    <div class="product_bubble product_bubble_right product_bubble_red d-flex flex-column align-items-center"><span>sale</span></div>
                                                }
                                                @* <div class="product_bubble product_bubble_right product_bubble_red d-flex flex-column align-items-center"><span>-$20</span></div>*@
                                                <div class="product_info">
                                                    <h6 class="product_name"><a href="/chi-tiet/@item.Alias-p@(item.IDProduct)">@item.Name</a></h6>
                                                    @if (item.PriceSale > 0)
                                                    {
                                                        <div class="product_price">@BanHang.Common.Common.FormatNumber(item.PriceSale, 0)<span>@BanHang.Common.Common.FormatNumber(item.Price, 0)</span></div>
                                                        <div style="display:none;" class="in_product_price"> @item.PriceSale</div>
                                                    }
                                                    else
                                                    {
                                                        <div class="product_price">@BanHang.Common.Common.FormatNumber(item.Price, 0)</div>
                                                        <div style="display:none;" class="in_product_price"> @item.Price</div>
                                                    }
                                                </div>
                                            </div>
                                            <div class="red_button add_to_cart_button"><a href="#" class="btnAddToCart" data-id="@item.IDProduct">add to cart</a></div>
                                        </div>
                                    }
                                }


                            </div>

                            <!-- Product Sorting -->

                            <div class="product_sorting_container product_sorting_container_bottom clearfix">
                                <ul class="product_sorting">
                                    <li>
                                        <span>Hiển Thị:</span>
                                        <span class="num_sorting_text">04</span>
                                        <i class="fa fa-angle-down"></i>
                                        <ul class="sorting_num">
                                            <li class="num_sorting_btn"><span>01</span></li>
                                            <li class="num_sorting_btn"><span>02</span></li>
                                            <li class="num_sorting_btn"><span>03</span></li>
                                            <li class="num_sorting_btn"><span>04</span></li>
                                        </ul>
                                    </li>
                                </ul>
                                @*<span class="showing_results">Showing 1–3 of 12 results</span>*@
                                @*<div class="pages d-flex flex-row align-items-center">
                                        <div class="page_current">
                                            <span>1</span>
                                            <ul class="page_selection">
                                                <li><a href="#">1</a></li>
                                                <li><a href="#">2</a></li>
                                                <li><a href="#">3</a></li>
                                            </ul>
                                        </div>
                                        <div class="page_total"><span>of</span> 3</div>
                                        <div id="next_page_1" class="page_next"><a href="#"><i class="fa fa-long-arrow-right" aria-hidden="true"></i></a></div>
                                    </div>*@

                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container" style=" margin-bottom: 18px; margin-top: -40px;">
    <div class="row justify-content-center">
        <div class="col-12">
            @Html.PagedListPager(Model, page => Url.Action("ProductCategory", new { page, id = ViewBag.CateId, searchTitle = ViewBag.SearchTitle }))
        </div>
    </div>
</div>
@section scripts{
    <script src="~/Content/assets/js/categories_custom.js"></script>
}